version: "3"

services:
  boot:
    image: p2p-auction
    environment:
      - MODE=boot
      - ARGS=--key-path config/boot1 --port 63358
    networks:
      - p2p-net
  node:
    image: p2p-auction
    depends_on:
      boot:
        condition: service_started
        restart: true
    environment:
      - MODE=main
      - ARGS=--key-path config/node1
    networks:
      - p2p-net

networks:
  p2p-net:
    driver: bridge
